FROM ubuntu:22.04

WORKDIR /app
COPY frontend/conn .

ENV BACKEND_URL=${BACKEND_URL}

RUN apt-get update && \
    apt-get install -y curl git build-essential nginx

RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
    apt-get install -y nodejs

RUN npm install -g npm@latest && \
    npm install && \
    npm run build

COPY nginx.conf /etc/nginx/nginx.conf
#COPY fullchain.pem /etc/nginx/ssl/fullchain.pem 
#COPY privkey.pem /etc/nginx/ssl/privkey.pem

EXPOSE 80
EXPOSE 443

CMD nginx -g "daemon off;"
