
events {
	worker_connections 1024;
}

http {
	
	server {
		include mime.types;
		server_name 217.25.94.71;
		listen 80;

		location /api/ {
			include proxy_params;
			proxy_pass http://10.168.0.2:8000;
		}

		location /assets {
			expires 7d;
			root /app/dist;
		}

		location / {
			root /app/dist;
			index index.html;
		}

		
	}
}
