# Generated by Django 5.2.2 on 2025-06-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('otchestvo', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
            ],
        ),
    ]
