# Generated by Django 5.2.2 on 2025-06-08 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mac_addr', models.CharField(max_length=18, unique=True)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('comment', models.CharField(max_length=2000)),
                ('given_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff')),
            ],
        ),
    ]
