# Generated by Django 5.2.2 on 2025-06-23 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.users'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='mac_addr',
            field=models.CharField(max_length=18, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='serial_number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
