# Generated by Django 5.2.2 on 2025-07-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_devices_user_alter_devices_mac_addr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='model',
            field=models.CharField(default='123', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devices',
            name='name',
            field=models.CharField(default='Устройство', max_length=255, null=True),
        ),
    ]
