# Generated by Django 5.2.2 on 2025-06-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connections',
            name='vlan',
            field=models.CharField(default='123', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='connections',
            name='type_conn',
            field=models.CharField(choices=[('ipoe', 'Динамический IP'), ('pptp', 'Point-To-Point Tunneling Protocol'), ('static', 'Статический Ethernet IP'), ('L2', 'L2 канал'), ('openvpn', 'openvpn')]),
        ),
    ]
