# Generated by Django 5.2.2 on 2025-06-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0002_connections_vlan_alter_connections_type_conn'),
    ]

    operations = [
        migrations.AddField(
            model_name='connections',
            name='name',
            field=models.CharField(default='123', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
