# Generated by Django 5.2.2 on 2025-06-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0003_connections_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='connections',
            name='addr',
            field=models.CharField(default='г. Калининград ул. Минская д. 10 кв. 1', max_length=500),
            preserve_default=False,
        ),
    ]
