# Generated by Django 5.2.2 on 2025-06-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0004_connections_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connections',
            name='vlan',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
