# Generated by Django 5.2.2 on 2025-07-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0005_alter_connections_vlan'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connections',
            unique_together={('name', 'vlan')},
        ),
    ]
