# Generated by Django 5.2.2 on 2025-07-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0006_alter_connections_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connections',
            name='vlan',
            field=models.CharField(blank=True, default='123', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
