# Generated by Django 5.2.2 on 2025-07-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0007_alter_connections_vlan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connections',
            name='vlan',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
