# Generated by Django 5.2.2 on 2025-06-27 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0002_connections_vlan_alter_connections_type_conn'),
        ('switches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('untgd_vlan', models.IntegerField()),
                ('macs', models.IntegerField()),
                ('connector', models.CharField(choices=[('RJ45', 'RJ45 / мед.'), ('RJ11', 'RJ11 / мед.'), ('RS232', 'RS232 / мед.'), ('FC', 'FC / опт.'), ('ST', 'ST / опт.'), ('QSFP', 'QSFP / опт.'), ('N-Type', 'N-Type / рад.'), ('SMA', 'SMA / рад.'), ('RP-SMA', 'RP-SMA / рад.')], max_length=50)),
                ('comment', models.CharField(max_length=355)),
            ],
        ),
        migrations.AddField(
            model_name='switches',
            name='ports',
            field=models.ManyToManyField(to='switches.port'),
        ),
        migrations.CreateModel(
            name='PortThroughConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connection.connections')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='switches.port')),
            ],
            options={
                'unique_together': {('connection', 'port')},
            },
        ),
        migrations.AddField(
            model_name='port',
            name='client',
            field=models.ManyToManyField(through='switches.PortThroughConnection', to='connection.connections'),
        ),
    ]
