# Generated by Django 5.2.2 on 2025-06-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0002_port_switches_ports_portthroughconnection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='switches',
            name='name',
            field=models.CharField(default='Switch Октябрьская 1', max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
