# Generated by Django 5.2.2 on 2025-06-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0003_switches_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='comment',
            field=models.CharField(max_length=355, null=True),
        ),
    ]
