# Generated by Django 5.2.2 on 2025-06-29 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0005_alter_connections_vlan'),
        ('switches', '0004_alter_port_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portthroughconnection',
            name='connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connection.connections'),
        ),
        migrations.CreateModel(
            name='SwitchThroughPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='switches.port')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='switches.switches')),
            ],
            options={
                'unique_together': {('switch', 'port')},
            },
        ),
    ]
