# Generated by Django 5.2.2 on 2025-07-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0006_alter_connections_unique_together'),
        ('switches', '0005_rename_client_port_connection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='connection',
        ),
        migrations.AlterUniqueTogether(
            name='switchthroughport',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='switchthroughport',
            name='port',
        ),
        migrations.RemoveField(
            model_name='switchthroughport',
            name='switch',
        ),
        migrations.AddField(
            model_name='port',
            name='connections',
            field=models.ManyToManyField(to='connection.connections'),
        ),
        migrations.DeleteModel(
            name='PortThroughConnection',
        ),
        migrations.DeleteModel(
            name='SwitchThroughPort',
        ),
    ]
