# Generated by Django 5.2.2 on 2025-07-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0007_alter_connections_vlan'),
        ('switches', '0006_remove_port_connection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='connections',
            field=models.ManyToManyField(blank=True, to='connection.connections'),
        ),
    ]
